//
//  MULTIPLAYER_GAME_LAUNCH_VALIDATOR.cpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 8/01/17.
//  Copyright © 2017 Christophe Bernard. All rights reserved.
//

#include "MULTIPLAYER_GAME_LAUNCH_VALIDATOR.h"

MULTIPLAYER_GAME_LAUNCH_VALIDATOR::MULTIPLAYER_GAME_LAUNCH_VALIDATOR() {
    
}

MULTIPLAYER_GAME_LAUNCH_VALIDATOR::~MULTIPLAYER_GAME_LAUNCH_VALIDATOR() {
    
}

void MULTIPLAYER_GAME_LAUNCH_VALIDATOR::Validate( GRAPHIC_UI_PRESENTER * presenter ) {
    
}
