//
//  GRAPHIC_UI_ELEMENT_STATE.h
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 21/06/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#ifndef __GAME_ENGINE_REBORN__GRAPHIC_UI_ELEMENT_STATE__
#define __GAME_ENGINE_REBORN__GRAPHIC_UI_ELEMENT_STATE__

enum GRAPHIC_UI_ELEMENT_STATE {
    GRAPHIC_UI_ELEMENT_STATE_Default = 0x0001,
    GRAPHIC_UI_ELEMENT_STATE_Hovered = 0x0010,
    GRAPHIC_UI_ELEMENT_STATE_Pressed = 0x0100,
    GRAPHIC_UI_ELEMENT_STATE_Disabled = 0x1000,
    GRAPHIC_UI_ELEMENT_STATE_Count,
    GRAPHIC_UI_ELEMENT_STATE_None
};

#endif /* defined(__GAME_ENGINE_REBORN__GRAPHIC_UI_ELEMENT_STATE__) */
