//
//  GRAPHIC_UI_PLACEMENT_ANCHOR.h
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 21/06/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#ifndef GAME_ENGINE_REBORN_GRAPHIC_UI_PLACEMENT_ANCHOR_h
#define GAME_ENGINE_REBORN_GRAPHIC_UI_PLACEMENT_ANCHOR_h

enum GRAPHIC_UI_PLACEMENT_ANCHOR {
    GRAPHIC_UI_PLACEMENT_ANCHOR_Left = 1,
    GRAPHIC_UI_PLACEMENT_ANCHOR_Right = 2,
    GRAPHIC_UI_PLACEMENT_ANCHOR_Top = 4,
    GRAPHIC_UI_PLACEMENT_ANCHOR_Bottom = 8,
    GRAPHIC_UI_PLACEMENT_ANCHOR_CenterX = 16,
    GRAPHIC_UI_PLACEMENT_ANCHOR_CenterY = 32,
    GRAPHIC_UI_PLACEMENT_ANCHOR_Count,
    GRAPHIC_UI_PLACEMENT_ANCHOR_None
};

#define GRAPHIC_UI_TopLeft \
    GRAPHIC_UI_PLACEMENT_ANCHOR_Left | GRAPHIC_UI_PLACEMENT_ANCHOR_Top

#define GRAPHIC_UI_TopRight \
    GRAPHIC_UI_PLACEMENT_ANCHOR_Right | GRAPHIC_UI_PLACEMENT_ANCHOR_Top

#define GRAPHIC_UI_BottomLeft \
    GRAPHIC_UI_PLACEMENT_ANCHOR_Left | GRAPHIC_UI_PLACEMENT_ANCHOR_Bottom

#define GRAPHIC_UI_BottomRight \
    GRAPHIC_UI_PLACEMENT_ANCHOR_Right | GRAPHIC_UI_PLACEMENT_ANCHOR_Bottom

#define GRAPHIC_UI_Right \
    GRAPHIC_UI_PLACEMENT_ANCHOR_Right | GRAPHIC_UI_PLACEMENT_ANCHOR_CenterY

#define GRAPHIC_UI_Left \
    GRAPHIC_UI_PLACEMENT_ANCHOR_Left | GRAPHIC_UI_PLACEMENT_ANCHOR_CenterY

#define GRAPHIC_UI_Top \
    GRAPHIC_UI_PLACEMENT_ANCHOR_CenterX | GRAPHIC_UI_PLACEMENT_ANCHOR_Top

#define GRAPHIC_UI_Bottom \
    GRAPHIC_UI_PLACEMENT_ANCHOR_CenterX | GRAPHIC_UI_PLACEMENT_ANCHOR_Bottom

#define GRAPHIC_UI_Center \
    GRAPHIC_UI_PLACEMENT_ANCHOR_CenterX | GRAPHIC_UI_PLACEMENT_ANCHOR_CenterY


#endif
