//
//  GRAPHIC_RENDER_TARGET_FRAMEBUFFER_MODE.h
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 24/06/18.
//  Copyright © 2018 Christophe Bernard. All rights reserved.
//

#ifndef GRAPHIC_RENDER_TARGET_FRAMEBUFFER_MODE_h
#define GRAPHIC_RENDER_TARGET_FRAMEBUFFER_MODE_h

enum GRAPHIC_RENDER_TARGET_FRAMEBUFFER_MODE {
    GRAPHIC_RENDER_TARGET_FRAMEBUFFER_MODE_All,
    GRAPHIC_RENDER_TARGET_FRAMEBUFFER_MODE_Write,
    GRAPHIC_RENDER_TARGET_FRAMEBUFFER_MODE_Read,
};

#endif /* GRAPHIC_RENDER_TARGET_FRAMEBUFFER_MODE_h */
