//
//  GAMEPLAY_COMPONENT_POSITION_INTERPOLATION.cpp
//  MULTIPOLY
//
//  Created by Christophe Bernard on 10/03/17.
//  Copyright © 2017 cbe. All rights reserved.
//

#include "GAMEPLAY_COMPONENT_POSITION_INTERPOLATION.h"


GAMEPLAY_COMPONENT_POSITION_INTERPOLATION::GAMEPLAY_COMPONENT_POSITION_INTERPOLATION() :
    GAMEPLAY_COMPONENT_SYSTEM() {
    
}

GAMEPLAY_COMPONENT_POSITION_INTERPOLATION::~GAMEPLAY_COMPONENT_POSITION_INTERPOLATION() {
    
}
