//
//  GAMEPLAY_COMPONENT_POSITION_INTERPOLATION.hpp
//  MULTIPOLY
//
//  Created by Christophe Bernard on 10/03/17.
//  Copyright © 2017 cbe. All rights reserved.
//

#ifndef GAMEPLAY_COMPONENT_POSITION_INTERPOLATION_hpp
#define GAMEPLAY_COMPONENT_POSITION_INTERPOLATION_hpp

#include "CORE_HELPERS_CLASS.h"
#include "GAMEPLAY_COMPONENT_SYSTEM.h"

XS_CLASS_BEGIN_WITH_ANCESTOR( GAMEPLAY_COMPONENT_POSITION_INTERPOLATION, GAMEPLAY_COMPONENT_SYSTEM )

    GAMEPLAY_COMPONENT_POSITION_INTERPOLATION();
    ~GAMEPLAY_COMPONENT_POSITION_INTERPOLATION();

XS_CLASS_END

#endif /* GAMEPLAY_COMPONENT_POSITION_INTERPOLATION_hpp */
