//
//  GAMEPLAY_ACTION_TYPE.h
//  MULTIPOLY
//
//  Created by Christophe Bernard on 5/03/17.
//  Copyright © 2017 cbe. All rights reserved.
//

#ifndef GAMEPLAY_ACTION_TYPE_h
#define GAMEPLAY_ACTION_TYPE_h

enum GAMEPLAY_ACTION_TYPE {
    
    GAMEPLAY_ACTION_TYPE_ClientConnected = 0,
    GAMEPLAY_ACTION_TYPE_ClientRejected,
    GAMEPLAY_ACTION_TYPE_ClientReady,
    GAMEPLAY_ACTION_TYPE_ClientQuit,
    GAMEPLAY_ACTION_TYPE_ClientAccepted, 
    GAMEPLAY_ACTION_TYPE_LoadGame,
    GAMEPLAY_ACTION_TYPE_GameStarting,
    GAMEPLAY_ACTION_TYPE_Custom_1,
    GAMEPLAY_ACTION_TYPE_Custom_2,
    GAMEPLAY_ACTION_TYPE_Custom_3,
    GAMEPLAY_ACTION_TYPE_Custom_4,
    GAMEPLAY_ACTION_TYPE_Custom_5,
    GAMEPLAY_ACTION_TYPE_Custom_6,
    GAMEPLAY_ACTION_TYPE_Custom_7,
    GAMEPLAY_ACTION_TYPE_Custom_8,
    GAMEPLAY_ACTION_TYPE_Custom_9,
    GAMEPLAY_ACTION_TYPE_Custom_10,
    GAMEPLAY_ACTION_TYPE_Custom_11,
    GAMEPLAY_ACTION_TYPE_Custom_12,
    GAMEPLAY_ACTION_TYPE_Custom_13,
    GAMEPLAY_ACTION_TYPE_Custom_14,
    GAMEPLAY_ACTION_TYPE_Custom_15,
    GAMEPLAY_ACTION_TYPE_Custom_16,
    GAMEPLAY_ACTION_TYPE_Custom_17,
    GAMEPLAY_ACTION_TYPE_Custom_18,
    GAMEPLAY_ACTION_TYPE_Custom_19,
    GAMEPLAY_ACTION_TYPE_Custom_20,
    GAMEPLAY_ACTION_TYPE_Custom_21,
    GAMEPLAY_ACTION_TYPE_Custom_22,
    GAMEPLAY_ACTION_TYPE_Custom_23,
    GAMEPLAY_ACTION_TYPE_Custom_24,
    GAMEPLAY_ACTION_TYPE_Custom_25,
    GAMEPLAY_ACTION_TYPE_Custom_26,
    GAMEPLAY_ACTION_TYPE_Custom_27,
    GAMEPLAY_ACTION_TYPE_Custom_28,
    GAMEPLAY_ACTION_TYPE_Custom_29,
    GAMEPLAY_ACTION_TYPE_Custom_30,
    GAMEPLAY_ACTION_TYPE_NONE
};


#endif /* GAMEPLAY_ACTION_TYPE_h */
