//
//  GRAPHIC_SYSTEM_BLEND_OPERATION.h
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 21/06/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#ifndef GAME_ENGINE_REBORN_GRAPHIC_SYSTEM_BLEND_OPERATION_h
#define GAME_ENGINE_REBORN_GRAPHIC_SYSTEM_BLEND_OPERATION_h

enum GRAPHIC_SYSTEM_BLEND_OPERATION {
    
    GRAPHIC_SYSTEM_BLEND_OPERATION_Zero = 0,
    GRAPHIC_SYSTEM_BLEND_OPERATION_One,
    GRAPHIC_SYSTEM_BLEND_OPERATION_SourceAlpha,
    GRAPHIC_SYSTEM_BLEND_OPERATION_DestinationAlpha,
    GRAPHIC_SYSTEM_BLEND_OPERATION_OneMinusSourceAlpha,
    GRAPHIC_SYSTEM_BLEND_OPERATION_OneMinusDestinationAlpha,
    GRAPHIC_SYSTEM_BLEND_OPERATION_Count,
    GRAPHIC_SYSTEM_BLEND_OPERATION_None
};

#endif
