//
//  GRAPHIC_SYSTEM_COMPARE_OPERATION.h
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 21/06/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#ifndef GAME_ENGINE_REBORN_GRAPHIC_SYSTEM_COMPARE_OPERATION_h
#define GAME_ENGINE_REBORN_GRAPHIC_SYSTEM_COMPARE_OPERATION_h

enum GRAPHIC_SYSTEM_COMPARE_OPERATION {
    GRAPHIC_SYSTEM_COMPARE_OPERATION_Never = 0,
    GRAPHIC_SYSTEM_COMPARE_OPERATION_Less,
    GRAPHIC_SYSTEM_COMPARE_OPERATION_Equal,
    GRAPHIC_SYSTEM_COMPARE_OPERATION_LessOrEqual,
    GRAPHIC_SYSTEM_COMPARE_OPERATION_GreaterOrEqual,
    GRAPHIC_SYSTEM_COMPARE_OPERATION_NotEqual,
    GRAPHIC_SYSTEM_COMPARE_OPERATION_Always,
    GRAPHIC_SYSTEM_COMPARE_OPERATION_Count,
    GRAPHIC_SYSTEM_COMPARE_OPERATION_None
};

#endif
