//
//  GRAPHIC_SYSTEM_BLEND_FUNCTION.h
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 10/11/2018.
//  Copyright © 2018 Christophe Bernard. All rights reserved.
//

#ifndef GRAPHIC_SYSTEM_BLEND_EQUATION_h
#define GRAPHIC_SYSTEM_BLEND_EQUATION_h

enum GRAPHIC_SYSTEM_BLEND_EQUATION {
    GRAPHIC_SYSTEM_BLEND_EQUATION_Add = 0,
    GRAPHIC_SYSTEM_BLEND_EQUATION_Substract,
    GRAPHIC_SYSTEM_BLEND_EQUATION_ReverseSubstract,
    GRAPHIC_SYSTEM_BLEND_EQUATION_Min,
    GRAPHIC_SYSTEM_BLEND_EQUATION_Max,
    GRAPHIC_SYSTEM_BLEND_EQUATION_Count,
    GRAPHIC_SYSTEM_BLEND_EQUATION_None = -1
};

#endif /* GRAPHIC_SYSTEM_BLEND_EQUATION_h */
