//
//  CORE_ABSTRACT_PROGRAM_V8.cpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 8/11/14.
//  Copyright (c) 2014 Christophe Bernard. All rights reserved.
//

#include "CORE_ABSTRACT_PROGRAM_V8.h"

CORE_ABSTRACT_PROGRAM_V8::CORE_ABSTRACT_PROGRAM_V8() : CORE_ABSTRACT_PROGRAM_FACTORY() {
    
}

CORE_ABSTRACT_PROGRAM_V8::CORE_ABSTRACT_PROGRAM_V8( const CORE_ABSTRACT_PROGRAM_V8 & other) : CORE_ABSTRACT_PROGRAM_FACTORY() {
    
}

CORE_ABSTRACT_PROGRAM_V8::~CORE_ABSTRACT_PROGRAM_V8() {
    
}

void CORE_ABSTRACT_PROGRAM_V8::Load( const char * path, const CORE_ABSTRACT_BASE_PROGRAM_RUNTIME & runtime) {
    
}

void CORE_ABSTRACT_PROGRAM_V8::Execute() {
    
}
