//
//  CORE_ABSTRACT_PROGRAM_RUNTIME_MANAGER.h
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 28/12/14.
//  Copyright (c) 2014 Christophe Bernard. All rights reserved.
//

#ifndef __GAME_ENGINE_REBORN__CORE_ABSTRACT_PROGRAM_RUNTIME_MANAGER__
#define __GAME_ENGINE_REBORN__CORE_ABSTRACT_PROGRAM_RUNTIME_MANAGER__

#include "CORE_HELPERS_CLASS.h"
#include "CORE_HELPERS_UNIQUE.h"
#include "CORE_ABSTRACT_PROGRAM_RUNTIME_TYPE.h"
#include "CORE_ABSTRACT_BASE_PROGRAM_RUNTIME.h"
#include "CORE_HELPERS_IDENTIFIER.h"

XS_CLASS_BEGIN(CORE_ABSTRACT_PROGRAM_RUNTIME_MANAGER)

XS_DEFINE_UNIQUE(CORE_ABSTRACT_PROGRAM_RUNTIME_MANAGER)

~CORE_ABSTRACT_PROGRAM_RUNTIME_MANAGER();

void Initialize();

std::map<CORE_ABSTRACT_PROGRAM_RUNTIME_TYPE, CORE_ABSTRACT_BASE_PROGRAM_RUNTIME * > & getDefaultProgramRuntimeTable() {
    
    return DefaultProgramRuntimeTable;
}

std::map<CORE_HELPERS_IDENTIFIER, CORE_ABSTRACT_BASE_PROGRAM_RUNTIME * > & getCustomProgramRuntimeTable() {
    
    return CustomProgramRuntimeTable;
}

private :

std::map<CORE_ABSTRACT_PROGRAM_RUNTIME_TYPE, CORE_ABSTRACT_BASE_PROGRAM_RUNTIME * > DefaultProgramRuntimeTable;
std::map<CORE_HELPERS_IDENTIFIER, CORE_ABSTRACT_BASE_PROGRAM_RUNTIME * > CustomProgramRuntimeTable;

XS_CLASS_END

#endif /* defined(__GAME_ENGINE_REBORN__CORE_ABSTRACT_PROGRAM_RUNTIME_MANAGER__) */
