//
//  CORE_ABSTRACT_BASE_PROGRAM_RUNTIME.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 7/01/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#include "CORE_ABSTRACT_BASE_PROGRAM_RUNTIME.h"

CORE_ABSTRACT_BASE_PROGRAM_RUNTIME::CORE_ABSTRACT_BASE_PROGRAM_RUNTIME() {

}

CORE_ABSTRACT_BASE_PROGRAM_RUNTIME::~CORE_ABSTRACT_BASE_PROGRAM_RUNTIME() {

}
