//
//  CORE_ABSTRACT_BASE_PROGRAM_RUNTIME.h
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 7/01/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#ifndef __GAME_ENGINE_REBORN__CORE_ABSTRACT_BASE_PROGRAM_RUNTIME__
#define __GAME_ENGINE_REBORN__CORE_ABSTRACT_BASE_PROGRAM_RUNTIME__

#include "CORE_HELPERS_CLASS.h"

XS_CLASS_BEGIN(CORE_ABSTRACT_BASE_PROGRAM_RUNTIME)

CORE_ABSTRACT_BASE_PROGRAM_RUNTIME();

XS_CLASS_END

#endif /* defined(__GAME_ENGINE_REBORN__CORE_ABSTRACT_BASE_PROGRAM_RUNTIME__) */
