//
//  CORE_ABSTRACT_PROGRAM_BINDER_MODE.h
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 28/11/14.
//  Copyright (c) 2014 Christophe Bernard. All rights reserved.
//

#ifndef GAME_ENGINE_REBORN_CORE_ABSTRACT_PROGRAM_BINDER_MODE_h
#define GAME_ENGINE_REBORN_CORE_ABSTRACT_PROGRAM_BINDER_MODE_h

enum CORE_ABSTRACT_PROGRAM_BINDER_MODE {
    CORE_ABSTRACT_PROGRAM_BINDER_MODE_None = 0,
    CORE_ABSTRACT_PROGRAM_BINDER_MODE_Public,
    CORE_ABSTRACT_PROGRAM_BINDER_MODE_Private,
    CORE_ABSTRACT_PROGRAM_BINDER_MODE_Count
};

#endif
