//
//  CORE_ABSTRACT_FUNCTION.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 23/01/16.
//  Copyright © 2016 Christophe Bernard. All rights reserved.
//

#include "CORE_ABSTRACT_FUNCTION.h"

/*CORE_ABSTRACT_PROGRAM_BINDER_DECLARE_CLASS( CORE_ABSTRACT_FUNCTION )
    CORE_ABSTRACT_PROGRAM_BINDER_DEFINE_VOID_METHOD_1(CORE_ABSTRACT_FUNCTION, Initialize, const char *)
CORE_ABSTRACT_PROGRAM_BINDER_END_CLASS( CORE_ABSTRACT_FUNCTION )*/

