//
//  GRAPHIC_SYSTEM_POLYGON_FILL_MODE.h
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 21/06/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#ifndef GAME_ENGINE_REBORN_GRAPHIC_SYSTEM_POLYGON_FILL_MODE_h
#define GAME_ENGINE_REBORN_GRAPHIC_SYSTEM_POLYGON_FILL_MODE_h

enum GRAPHIC_SYSTEM_POLYGON_FILL_MODE {

    GRAPHIC_SYSTEM_POLYGON_FILL_MODE_Point,
    GRAPHIC_SYSTEM_POLYGON_FILL_MODE_Line,
    GRAPHIC_SYSTEM_POLYGON_FILL_MODE_Full,
    GRAPHIC_SYSTEM_POLYGON_FILL_MODE_Count,
    GRAPHIC_SYSTEM_POLYGON_FILL_MODE_None
};

#endif
