//
//  PERIPHERIC_INTERACTION_TOUCH.h
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 16/04/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#ifndef __GAME_ENGINE_REBORN__PERIPHERIC_INTERACTION_TOUCH__
#define __GAME_ENGINE_REBORN__PERIPHERIC_INTERACTION_TOUCH__

#include "CORE_HELPERS_CLASS.h"

XS_CLASS_BEGIN( PERIPHERIC_INTERACTION_TOUCH )



XS_CLASS_END

#endif /* defined(__GAME_ENGINE_REBORN__PERIPHERIC_INTERACTION_TOUCH__) */
