//
//  CORE_ABSTRACT_PROGRAM_NATIVELIBRARY.hpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 08/04/2019.
//  Copyright © 2019 Christophe Bernard. All rights reserved.
//

#ifndef CORE_ABSTRACT_PROGRAM_NATIVELIBRARY_hpp
#define CORE_ABSTRACT_PROGRAM_NATIVELIBRARY_hpp

#include "CORE_HELPERS_CLASS.h"
#include "CORE_ABSTRACT_PROGRAM_RUNTIME.h"

XS_CLASS_BEGIN_WITH_ANCESTOR( CORE_ABSTRACT_PROGRAM_NATIVELIBRARY, CORE_ABSTRACT_PROGRAM_RUNTIME< CORE_ABSTRACT_PROGRAM_NATIVELIBRARY >)

    CORE_HELPERS_FACTORY_Element(CORE_ABSTRACT_PROGRAM_NATIVELIBRARY, CORE_ABSTRACT_PROGRAM_FACTORY, CORE_ABSTRACT_PROGRAM_RUNTIME_TYPE, CORE_ABSTRACT_PROGRAM_RUNTIME_NATIVELIBRARY)

    CORE_ABSTRACT_PROGRAM_NATIVELIBRARY();
    virtual ~CORE_ABSTRACT_PROGRAM_NATIVELIBRARY();

    virtual void Load( const char *, const CORE_ABSTRACT_BASE_PROGRAM_RUNTIME &) override;
    virtual void Execute() override;

    virtual void Finalize() override;

#if PLATFORM_OSX
    void * LibraryHandle;
#else
    #error "TODO"
#endif

XS_CLASS_END

#endif /* CORE_ABSTRACT_PROGRAM_NATIVELIBRARY_hpp */
