//
//  APPLICATION_GAMEPLAY_COMMAND_LOAD_GAME.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 22/01/17.
//  Copyright © 2017 Christophe Bernard. All rights reserved.
//

#include "APPLICATION_COMMAND.h"

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( APPLICATION_GAMEPLAY_COMMAND_LOAD_GAME )

XS_END_INTERNAL_MEMORY_LAYOUT

ImplementTrickFroSerializeation( APPLICATION_GAMEPLAY_COMMAND_LOAD_GAME, APPLICATION_GAMEPLAY_COMMAND_LoadGame)

void APPLICATION_GAMEPLAY_COMMAND_LOAD_GAME::Apply() {
    
    OnGameLoaded();
}


CORE_HELPERS_CALLBACK APPLICATION_GAMEPLAY_COMMAND_LOAD_GAME::OnGameLoaded;
