//
//  APPLICATION_GAMEPLAY_COMMAND_ORDER_ATTACK.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 12/02/16.
//  Copyright © 2016 Christophe Bernard. All rights reserved.
//

#include "APPLICATION_COMMAND.h"
#include "CORE_DATA_JSON.h"

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( APPLICATION_GAMEPLAY_COMMAND_ORDER_ATTACK )

XS_END_INTERNAL_MEMORY_LAYOUT

ImplementTrickFroSerializeation(APPLICATION_GAMEPLAY_COMMAND_ORDER_ATTACK, APPLICATION_GAMEPLAY_COMMAND_OrderAttack)
