//
//  APPLICATION_NETWORK_COMMAND_CLIENT_QUIT.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 12/02/16.
//  Copyright © 2016 Christophe Bernard. All rights reserved.
//

#include "APPLICATION_COMMAND.h"

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( APPLICATION_NETWORK_COMMAND_CLIENT_QUIT )
    XS_DEFINE_ClassMember( "ClientIdentifier", CORE_HELPERS_UNIQUE_IDENTIFIER, ClientIdentifier )
XS_END_INTERNAL_MEMORY_LAYOUT

ImplementTrickFroSerializeation(APPLICATION_NETWORK_COMMAND_CLIENT_QUIT, APPLICATION_NETWORK_COMMAND_ClientQuit)
