//
//  APPLICATION_GAMEPLAY_COMMAND_GAME_STARTING.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 15/01/17.
//  Copyright © 2017 Christophe Bernard. All rights reserved.
//

#include "APPLICATION_COMMAND.h"

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( APPLICATION_GAMEPLAY_COMMAND_GAME_STARTING )

XS_END_INTERNAL_MEMORY_LAYOUT

ImplementTrickFroSerializeation(APPLICATION_GAMEPLAY_COMMAND_GAME_STARTING, APPLICATION_GAMEPLAY_COMMAND_GameStarting)

void APPLICATION_GAMEPLAY_COMMAND_GAME_STARTING::Apply() {
    
    
}
