//
//  APPLICATION_GAMEPLAY_COMMAND_ORDER_MOVE.cpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 11/02/16.
//  Copyright © 2016 Christophe Bernard. All rights reserved.
//

#include "APPLICATION_COMMAND.h"

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( APPLICATION_GAMEPLAY_COMMAND_ORDER_MOVE )

XS_END_INTERNAL_MEMORY_LAYOUT

ImplementTrickFroSerializeation(APPLICATION_GAMEPLAY_COMMAND_ORDER_MOVE, APPLICATION_GAMEPLAY_COMMAND_OrderMove)
