//
//  APPLICATION_NETWORK_COMMAND_CLIENT_READY.cpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 12/02/16.
//  Copyright © 2016 Christophe Bernard. All rights reserved.
//

#include "APPLICATION_COMMAND.h"

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( APPLICATION_NETWORK_COMMAND_CLIENT_READY )

XS_END_INTERNAL_MEMORY_LAYOUT

ImplementTrickFroSerializeation(APPLICATION_NETWORK_COMMAND_CLIENT_READY, APPLICATION_NETWORK_COMMAND_ClientReady)
