//
//  GAMEPLAY_ACTION_ROLL_DICE.hpp
//  MULTIPOLY
//
//  Created by Christophe Bernard on 11/03/17.
//  Copyright © 2017 cbe. All rights reserved.
//

#ifndef GAMEPLAY_ACTION_ROLL_DICE_hpp
#define GAMEPLAY_ACTION_ROLL_DICE_hpp

#include "GAMEPLAY_ACTION.h"
#include "GAMEPLAY_DICE_ROLL_RESULT.h"

XS_CLASS_BEGIN_WITH_ANCESTOR(GAMEPLAY_ACTION_ROLL_DICE, GAMEPLAY_ACTION )

    GAMEPLAY_ACTION_ROLL_DICE();
    GAMEPLAY_ACTION_ROLL_DICE( GAMEPLAY_DICE_ROLL_RESULT & result );

    ~GAMEPLAY_ACTION_ROLL_DICE();

    XS_DEFINE_SERIALIZABLE

    CORE_HELPERS_FACTORY_Element( GAMEPLAY_ACTION_ROLL_DICE, GAMEPLAY_ACTION, GAMEPLAY_ACTION_TYPE, GAMEPLAY_ACTION_TYPE_Custom_4 )

    virtual void Apply() override;

    SimpleTrickForSerialization()

    GAMEPLAY_DICE_ROLL_RESULT
        Result;
XS_CLASS_END

#endif /* GAMEPLAY_ACTION_ROLL_DICE_hpp */
