//
//  CORE_ABSTRACT_PROGRAM_LUA_HELPERS_CALLBACK_UI.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 31/01/16.
//  Copyright © 2016 Christophe Bernard. All rights reserved.
//

#include "CORE_ABSTRACT_PROGRAM_LUA_HELPERS.h"
#include "GRAPHIC_UI_ELEMENT.h"

typedef CORE_HELPERS_CALLBACK_2< GRAPHIC_UI_ELEMENT *, GRAPHIC_UI_ELEMENT_STATE > XS_UI_CALLBACK;

CORE_ABSTRACT_PROGRAM_BINDER_DECLARE_CLASS( XS_UI_CALLBACK )

CORE_ABSTRACT_PROGRAM_BINDER_END_TEMPLATE_CLASS( XS_UI_CALLBACK )
