//
//  GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR.cpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 25/10/15.
//  Copyright © 2015 Christophe Bernard. All rights reserved.
//

#include "GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR.h"

GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR::GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR() :
    GRAPHIC_SHADER_EFFECT() {
    
}

GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR::~GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR() {

}

void GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR::Apply() {
    
    
}

void GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR::BindAttributes() {
    
}

CORE_HELPERS_IDENTIFIER
    GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR::SampleOffsetsIdentifier( "SampleOffsets" ),
    GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR::SampleWeightsIdentifier( "SampleWeights" );