//
//  GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR.hpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 25/10/15.
//  Copyright © 2015 Christophe Bernard. All rights reserved.
//

#ifndef GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR_hpp
#define GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR_hpp

#include "CORE_HELPERS_CLASS.h"
#include "GRAPHIC_SHADER_EFFECT.h"

XS_CLASS_BEGIN_WITH_ANCESTOR( GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR, GRAPHIC_SHADER_EFFECT )

    GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR();
    virtual ~GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR();

    virtual void Apply() override;
    virtual void BindAttributes() override;

    static CORE_HELPERS_IDENTIFIER
        SampleOffsetsIdentifier,
        SampleWeightsIdentifier;

XS_CLASS_END


#endif /* GRAPHIC_SHADER_EFFECT_FULLSCREEN_GAUSSIAN_BLUR_hpp */
