//
//  GRAPHIC_UI_ELEMENT_STATE.h
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 21/06/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#ifndef __GAME_ENGINE_REBORN__GRAPHIC_UI_ELEMENT_STATE__
#define __GAME_ENGINE_REBORN__GRAPHIC_UI_ELEMENT_STATE__

enum GRAPHIC_UI_ELEMENT_STATE {
    GRAPHIC_UI_ELEMENT_STATE_Default = 0,
    GRAPHIC_UI_ELEMENT_STATE_Hovered,
    GRAPHIC_UI_ELEMENT_STATE_Pressed,
    GRAPHIC_UI_ELEMENT_STATE_Disabled,
    GRAPHIC_UI_ELEMENT_STATE_Count,
    GRAPHIC_UI_ELEMENT_STATE_None
};

#endif /* defined(__GAME_ENGINE_REBORN__GRAPHIC_UI_ELEMENT_STATE__) */
