//
//  RESOURCE_IMAGE_ATLAS.h
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 12/07/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#ifndef __GAME_ENGINE_REBORN__RESOURCE_IMAGE_ATLAS__
#define __GAME_ENGINE_REBORN__RESOURCE_IMAGE_ATLAS__

#include "CORE_HELPERS_CLASS.h"
#include "RESOURCE.h"
#include "RESOURCE_TYPE.h"
#include "GRAPHIC_TEXTURE_INFO.h"
#include "GRAPHIC_TEXTURE.h"
#include "RESOURCE_IMAGE.h"
#include "RESOURCE_TYPE.h"

XS_CLASS_BEGIN_WITH_ANCESTOR( RESOURCE_IMAGE_ATLAS, RESOURCE_IMAGE )

RESOURCE_IMAGE_ATLAS();

CORE_HELPERS_FACTORY_Element( RESOURCE_IMAGE_ATLAS, RESOURCE, RESOURCE_TYPE, RESOURCE_TYPE_ImageAtlasPng )

XS_CLASS_END

#endif /* defined(__GAME_ENGINE_REBORN__RESOURCE_IMAGE_ATLAS__) */
