//
//  GAMEPLAY_ACTION_COMMAND_SERVER_QUIT.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 19/12/17.
//  Copyright © 2017 Christophe Bernard. All rights reserved.
//

#include "GAMEPLAY_ACTION_COMMAND_SERVER_QUIT.h"
#include "CORE_DATA_JSON.h"

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( GAMEPLAY_ACTION_COMMAND_SERVER_QUIT )

XS_END_INTERNAL_MEMORY_LAYOUT

ImplementTrickFroSerializeation(GAMEPLAY_ACTION_COMMAND_SERVER_QUIT, GAMEPLAY_ACTION_TYPE_ServerQuit)

GAMEPLAY_ACTION_COMMAND_SERVER_QUIT::GAMEPLAY_ACTION_COMMAND_SERVER_QUIT() :
    GAMEPLAY_ACTION() {
    
}

GAMEPLAY_ACTION_COMMAND_SERVER_QUIT::GAMEPLAY_ACTION_COMMAND_SERVER_QUIT( const GAMEPLAY_ACTION_COMMAND_SERVER_QUIT & other ) :
    GAMEPLAY_ACTION()  {
    
    CORE_RUNTIME_Abort();
}

GAMEPLAY_ACTION_COMMAND_SERVER_QUIT::~GAMEPLAY_ACTION_COMMAND_SERVER_QUIT() {
    
}

void GAMEPLAY_ACTION_COMMAND_SERVER_QUIT::Apply() {
    
}
