//
//  GAMEPLAY_ACTION_COMMAND_CLIENT_REJECTED.h
//  MULTIPOLY
//
//  Created by Christophe Bernard on 5/03/17.
//  Copyright © 2017 cbe. All rights reserved.
//

#ifndef GAMEPLAY_ACTION_COMMAND_CLIENT_REJECTED_h
#define GAMEPLAY_ACTION_COMMAND_CLIENT_REJECTED_h

#include "GAMEPLAY_ACTION.h"
#include "NETWORK_PLAYER.h"

XS_CLASS_BEGIN_WITH_ANCESTOR( GAMEPLAY_ACTION_COMMAND_CLIENT_REJECTED,  GAMEPLAY_ACTION )
    XS_DEFINE_SERIALIZABLE

    GAMEPLAY_ACTION_COMMAND_CLIENT_REJECTED();
    ~GAMEPLAY_ACTION_COMMAND_CLIENT_REJECTED();

    CORE_HELPERS_FACTORY_Element( GAMEPLAY_ACTION_COMMAND_CLIENT_REJECTED, GAMEPLAY_ACTION, GAMEPLAY_ACTION_TYPE, GAMEPLAY_ACTION_TYPE_ClientRejected );

    SimpleTrickForSerialization()

    virtual void Apply() override;

    static CORE_HELPERS_CALLBACK_1< NETWORK_PLAYER * >
        ClientFromServerConnectionResponseCallback;

XS_CLASS_END

#endif /* GAMEPLAY_ACTION_COMMAND_CLIENT_REJECTED_h */
