//
//  GAMEPLAY_ACTION_COMMAND_SERVER_INFO.hpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 20/12/17.
//  Copyright © 2017 Christophe Bernard. All rights reserved.
//

#ifndef GAMEPLAY_ACTION_COMMAND_SERVER_INFO_hpp
#define GAMEPLAY_ACTION_COMMAND_SERVER_INFO_hpp

#include "GAMEPLAY_ACTION.h"
#include "NETWORK_PLAYER.h"
#include "NETWORK_SERVER_INFO.h"

XS_CLASS_BEGIN_WITH_ANCESTOR( GAMEPLAY_ACTION_COMMAND_SERVER_INFO, GAMEPLAY_ACTION )

    GAMEPLAY_ACTION_COMMAND_SERVER_INFO();
    virtual ~GAMEPLAY_ACTION_COMMAND_SERVER_INFO() {
        
    }

    XS_DEFINE_SERIALIZABLE

    CORE_HELPERS_FACTORY_Element( GAMEPLAY_ACTION_COMMAND_SERVER_INFO, GAMEPLAY_ACTION, GAMEPLAY_ACTION_TYPE, GAMEPLAY_ACTION_TYPE_ServerInfo )

    virtual void Apply() override;

    SimpleTrickForSerialization()

    std::vector< NETWORK_PLAYER::PTR >
        Players;
    NETWORK_SERVER_INFO
        * Info;

XS_CLASS_END

#endif /* GAMEPLAY_ACTION_COMMAND_SERVER_INFO_hpp */
