//
//  GAMEPLAY_ACTION_COMMAND_SERVER_INFO.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 20/12/17.
//  Copyright © 2017 Christophe Bernard. All rights reserved.
//

#include "GAMEPLAY_ACTION_COMMAND_SERVER_INFO.h"
#include "CORE_DATA_JSON.h"

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( GAMEPLAY_ACTION_COMMAND_SERVER_INFO )
    XS_DEFINE_ClassMember( "Players", std::vector< NETWORK_PLAYER::PTR >, Players )
    XS_DEFINE_ClassMember( "Info", NETWORK_SERVER_INFO *, Info )
XS_END_INTERNAL_MEMORY_LAYOUT

ImplementTrickFroSerializeation( GAMEPLAY_ACTION_COMMAND_SERVER_INFO, GAMEPLAY_ACTION_TYPE_ServerInfo )

GAMEPLAY_ACTION_COMMAND_SERVER_INFO::GAMEPLAY_ACTION_COMMAND_SERVER_INFO() :
    GAMEPLAY_ACTION(),
    Players(),
    Info( new NETWORK_SERVER_INFO()) {
    
}

GAMEPLAY_ACTION_COMMAND_SERVER_INFO::GAMEPLAY_ACTION_COMMAND_SERVER_INFO( const GAMEPLAY_ACTION_COMMAND_SERVER_INFO & other ) :
    GAMEPLAY_ACTION() {
    
    CORE_RUNTIME_Abort();
}

void GAMEPLAY_ACTION_COMMAND_SERVER_INFO::Apply() {
    
}
