//
//  APPLICATION_NETWORK_COMMAND_CLIENT_READY.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 12/02/16.
//  Copyright © 2016 Christophe Bernard. All rights reserved.
//

#include "GAMEPLAY_ACTION_COMMAND_CLIENT_READY.h"
#include "CORE_DATA_JSON.h"

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( GAMEPLAY_ACTION_COMMAND_CLIENT_READY )
    XS_DEFINE_ClassMember( "Player", NETWORK_PLAYER *, Player )
    XS_DEFINE_ClassMember( "Ready", bool, Ready )
XS_END_INTERNAL_MEMORY_LAYOUT

ImplementTrickFroSerializeation( GAMEPLAY_ACTION_COMMAND_CLIENT_READY, GAMEPLAY_ACTION_TYPE_ClientReady)

GAMEPLAY_ACTION_COMMAND_CLIENT_READY::GAMEPLAY_ACTION_COMMAND_CLIENT_READY() :
    GAMEPLAY_ACTION() {
    
}

GAMEPLAY_ACTION_COMMAND_CLIENT_READY::GAMEPLAY_ACTION_COMMAND_CLIENT_READY( const GAMEPLAY_ACTION_COMMAND_CLIENT_READY & other ) :
GAMEPLAY_ACTION() {
    abort();
}

GAMEPLAY_ACTION_COMMAND_CLIENT_READY::~GAMEPLAY_ACTION_COMMAND_CLIENT_READY() {
    
}

void GAMEPLAY_ACTION_COMMAND_CLIENT_READY::Apply() {
    
}
