//
//  GAMEPLAY_ACTION_COMMAND_SERVER_QUIT.hpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 19/12/17.
//  Copyright © 2017 Christophe Bernard. All rights reserved.
//

#ifndef GAMEPLAY_ACTION_COMMAND_SERVER_QUIT_hpp
#define GAMEPLAY_ACTION_COMMAND_SERVER_QUIT_hpp

#include "GAMEPLAY_ACTION.h"
#include "NETWORK_PLAYER.h"

XS_CLASS_BEGIN_WITH_ANCESTOR(GAMEPLAY_ACTION_COMMAND_SERVER_QUIT, GAMEPLAY_ACTION )

    GAMEPLAY_ACTION_COMMAND_SERVER_QUIT();
    ~GAMEPLAY_ACTION_COMMAND_SERVER_QUIT();

    XS_DEFINE_SERIALIZABLE

    CORE_HELPERS_FACTORY_Element( GAMEPLAY_ACTION_COMMAND_SERVER_QUIT, GAMEPLAY_ACTION, GAMEPLAY_ACTION_TYPE, GAMEPLAY_ACTION_TYPE_ServerQuit )

    virtual void Apply() override;

    SimpleTrickForSerialization()

XS_CLASS_END

#endif /* GAMEPLAY_ACTION_COMMAND_SERVER_QUIT_hpp */
