//
//  GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT.h
//  MULTIPOLY
//
//  Created by Christophe Bernard on 5/03/17.
//  Copyright © 2017 cbe. All rights reserved.
//

#ifndef GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT_h
#define GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT_h

#include "GAMEPLAY_ACTION.h"

XS_CLASS_BEGIN_WITH_ANCESTOR(GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT,  GAMEPLAY_ACTION )

    GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT();
    virtual ~GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT();

    XS_DEFINE_SERIALIZABLE

    CORE_HELPERS_FACTORY_Element( GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT, GAMEPLAY_ACTION, GAMEPLAY_ACTION_TYPE, GAMEPLAY_ACTION_TYPE_ClientQuit )

    virtual void Apply() override;

    SimpleTrickForSerialization()

private:
    CORE_HELPERS_UNIQUE_IDENTIFIER
        ClientIdentifier;

XS_CLASS_END

#endif /* GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT_h */
