//
//  APPLICATION_NETWORK_COMMAND_CLIENT_QUIT.cpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 12/02/16.
//  Copyright © 2016 Christophe Bernard. All rights reserved.
//

#include "GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT.h"

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT )
    XS_DEFINE_ClassMember( CORE_HELPERS_UNIQUE_IDENTIFIER, ClientIdentifier )
XS_END_INTERNAL_MEMORY_LAYOUT

ImplementTrickFroSerializeation(GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT, GAMEPLAY_ACTION_TYPE_ClientQuit)

GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT::GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT() :
    GAMEPLAY_ACTION(),
    ClientIdentifier() {
    
}

GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT::GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT( const GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT & other) :
GAMEPLAY_ACTION(),
ClientIdentifier() {
    abort();
}

GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT::~GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT() {
    
}


void GAMEPLAY_ACTION_COMMAND_CLIENT_QUIT::Apply() {
    
}
