//
//  GAMEPLAY_ACTION_COMMAND_CLIENT_READY.h
//  MULTIPOLY
//
//  Created by Christophe Bernard on 5/03/17.
//  Copyright © 2017 cbe. All rights reserved.
//

#ifndef GAMEPLAY_ACTION_COMMAND_CLIENT_READY_h
#define GAMEPLAY_ACTION_COMMAND_CLIENT_READY_h

#include "GAMEPLAY_ACTION.h"
#include "NETWORK_PLAYER.h"

XS_CLASS_BEGIN_WITH_ANCESTOR(GAMEPLAY_ACTION_COMMAND_CLIENT_READY, GAMEPLAY_ACTION )

    GAMEPLAY_ACTION_COMMAND_CLIENT_READY();
    virtual ~GAMEPLAY_ACTION_COMMAND_CLIENT_READY();

    XS_DEFINE_SERIALIZABLE

    CORE_HELPERS_FACTORY_Element( GAMEPLAY_ACTION_COMMAND_CLIENT_READY, GAMEPLAY_ACTION, GAMEPLAY_ACTION_TYPE, GAMEPLAY_ACTION_TYPE_ClientReady )

    virtual void Apply() override;

    SimpleTrickForSerialization()

    NETWORK_PLAYER
        * Player;
XS_CLASS_END

#endif /* GAMEPLAY_ACTION_COMMAND_CLIENT_READY_h */
