//
//  GAMEPLAY_ACTION_COMMAND_CLIENT_GAME_LOADED.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 11/02/18.
//  Copyright © 2018 Christophe Bernard. All rights reserved.
//

#include "GAMEPLAY_ACTION_COMMAND_GAME_LOADED.h"
#include "CORE_DATA_JSON.h"

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( GAMEPLAY_ACTION_COMMAND_GAME_LOADED )
    XS_DEFINE_ClassMember( "Player", NETWORK_PLAYER, &Player )
XS_END_INTERNAL_MEMORY_LAYOUT

ImplementTrickFroSerializeation( GAMEPLAY_ACTION_COMMAND_GAME_LOADED, GAMEPLAY_ACTION_TYPE_GameLoaded )

GAMEPLAY_ACTION_COMMAND_GAME_LOADED::GAMEPLAY_ACTION_COMMAND_GAME_LOADED() :
    GAMEPLAY_ACTION(),
    Player() {
    
}

GAMEPLAY_ACTION_COMMAND_GAME_LOADED::GAMEPLAY_ACTION_COMMAND_GAME_LOADED( const GAMEPLAY_ACTION_COMMAND_GAME_LOADED & other) :
    GAMEPLAY_ACTION(),
    Player() {
    
    CORE_RUNTIME_Abort();
}

GAMEPLAY_ACTION_COMMAND_GAME_LOADED::GAMEPLAY_ACTION_COMMAND_GAME_LOADED( NETWORK_PLAYER * player ) :
    GAMEPLAY_ACTION(),
    Player( player ) {
        
}

GAMEPLAY_ACTION_COMMAND_GAME_LOADED::~GAMEPLAY_ACTION_COMMAND_GAME_LOADED() {
    
}

void GAMEPLAY_ACTION_COMMAND_GAME_LOADED::Apply() {
    
}
