//
//  APPLICATION_NETWORK_COMMAND_CLIENT_CONNECTED.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 10/02/16.
//  Copyright © 2016 Christophe Bernard. All rights reserved.
//

#include "GAMEPLAY_ACTION_COMMAND_CLIENT_CONNECTED.h"
#include "CORE_APPLICATION.h"
#include "SERVICE_NETWORK_LOBBY.h"
#include "CORE_DATA_JSON.h"

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( GAMEPLAY_ACTION_COMMAND_CLIENT_CONNECTED )
    XS_DEFINE_ClassMember( "Player", NETWORK_PLAYER, Player )
XS_END_INTERNAL_MEMORY_LAYOUT

GAMEPLAY_ACTION_COMMAND_CLIENT_CONNECTED::GAMEPLAY_ACTION_COMMAND_CLIENT_CONNECTED() :
    GAMEPLAY_ACTION(),
    Player( NULL ) {
    
}

GAMEPLAY_ACTION_COMMAND_CLIENT_CONNECTED::GAMEPLAY_ACTION_COMMAND_CLIENT_CONNECTED( const GAMEPLAY_ACTION_COMMAND_CLIENT_CONNECTED & other ) :
GAMEPLAY_ACTION(),
Player( NULL ) {
    
    CORE_RUNTIME_Abort();
}

GAMEPLAY_ACTION_COMMAND_CLIENT_CONNECTED::~GAMEPLAY_ACTION_COMMAND_CLIENT_CONNECTED() {
    
}

ImplementTrickFroSerializeation(GAMEPLAY_ACTION_COMMAND_CLIENT_CONNECTED, GAMEPLAY_ACTION_TYPE_ClientConnected)

void GAMEPLAY_ACTION_COMMAND_CLIENT_CONNECTED::Apply() {
    
    ClientConnectedCallback( Player );
}


CORE_HELPERS_CALLBACK_1< NETWORK_PLAYER * >
    GAMEPLAY_ACTION_COMMAND_CLIENT_CONNECTED::ClientConnectedCallback;
