//
//  GAMEPLAY_COMPONENT_BASE_ENTITY.hpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 21/09/17.
//  Copyright © 2017 Christophe Bernard. All rights reserved.
//

#ifndef GAMEPLAY_COMPONENT_BASE_ENTITY_hpp
#define GAMEPLAY_COMPONENT_BASE_ENTITY_hpp

#include "CORE_HELPERS_CLASS.h"
#include "GAMEPLAY_COMPONENT_ENTITY.h"

XS_CLASS_BEGIN_WITH_ANCESTOR( GAMEPLAY_COMPONENT_BASE_ENTITY, GAMEPLAY_COMPONENT_ENTITY )

    GAMEPLAY_COMPONENT_BASE_ENTITY();
    ~GAMEPLAY_COMPONENT_BASE_ENTITY();

XS_CLASS_END

#endif /* GAMEPLAY_COMPONENT_BASE_ENTITY_hpp */
