//
//  GAMEPLAY_COMPONENT_MATERIAL.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 28/09/2020.
//  Copyright © 2020 Christophe Bernard. All rights reserved.
//

#include "GAMEPLAY_COMPONENT_RENDER_MATERIAL.h"

GAMEPLAY_COMPONENT_RENDER_MATERIAL::GAMEPLAY_COMPONENT_RENDER_MATERIAL() :
    Material() {
    
}
GAMEPLAY_COMPONENT_RENDER_MATERIAL::~GAMEPLAY_COMPONENT_RENDER_MATERIAL() {
    
}

int GAMEPLAY_COMPONENT_RENDER_MATERIAL::ComponentType = GAMEPLAY_COMPONENT_TYPE_Material;
