//
//  GAMEPLAY_COMPONENT.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 28/03/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#include "GAMEPLAY_COMPONENT.h"
#include "CORE_DATA_JSON.h"

CORE_ABSTRACT_PROGRAM_BINDER_DECLARE_CLASS( GAMEPLAY_COMPONENT )

CORE_ABSTRACT_PROGRAM_BINDER_END_CLASS( GAMEPLAY_COMPONENT )

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( GAMEPLAY_COMPONENT )

XS_END_INTERNAL_MEMORY_LAYOUT

GAMEPLAY_COMPONENT::GAMEPLAY_COMPONENT( unsigned int size ) :
    Size( size ) {
    
}


GAMEPLAY_COMPONENT::GAMEPLAY_COMPONENT() :
    Size( sizeof( this ) ) {
    
}

GAMEPLAY_COMPONENT::~GAMEPLAY_COMPONENT() {

}
