//
//  GAMEPLAY_COMPONENT.cpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 28/03/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#include "GAMEPLAY_COMPONENT.h"

CORE_ABSTRACT_PROGRAM_BINDER_DECLARE_CLASS( GAMEPLAY_COMPONENT )

CORE_ABSTRACT_PROGRAM_BINDER_END_CLASS( GAMEPLAY_COMPONENT )

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( GAMEPLAY_COMPONENT )

XS_END_INTERNAL_MEMORY_LAYOUT

GAMEPLAY_COMPONENT::GAMEPLAY_COMPONENT() {
    
}

GAMEPLAY_COMPONENT::~GAMEPLAY_COMPONENT() {

}
