//
//  GAMEPLAY_COMPONENT_BASE_ENTITY.cpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 21/09/17.
//  Copyright © 2017 Christophe Bernard. All rights reserved.
//

#include "GAMEPLAY_COMPONENT_BASE_ENTITY.h"

GAMEPLAY_COMPONENT_BASE_ENTITY::GAMEPLAY_COMPONENT_BASE_ENTITY() :
    GAMEPLAY_COMPONENT_ENTITY( this ) {
    
}

GAMEPLAY_COMPONENT_BASE_ENTITY::~GAMEPLAY_COMPONENT_BASE_ENTITY() {
    
}
