//
//  GAMEPLAY_COMPONENT.h
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 28/03/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#ifndef __GAME_ENGINE_REBORN__GAMEPLAY_COMPONENT__
#define __GAME_ENGINE_REBORN__GAMEPLAY_COMPONENT__

#include "CORE_HELPERS_CLASS.h"
#include "CORE_HELPERS_FACTORY.h"
#include "GAMEPLAY_COMPONENT_TYPE.h"

XS_CLASS_BEGIN( GAMEPLAY_COMPONENT )

GAMEPLAY_COMPONENT();
virtual ~GAMEPLAY_COMPONENT();

CORE_HELPERS_FACTORY_Define(GAMEPLAY_COMPONENT, GAMEPLAY_COMPONENT_TYPE )

XS_CLASS_END

#endif /* defined(__GAME_ENGINE_REBORN__GAMEPLAY_COMPONENT__) */
