//
//  GAMEPLAY_COMPONENT_ENTITY_PROXY.cpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 21/06/17.
//  Copyright © 2017 Christophe Bernard. All rights reserved.
//

#include "GAMEPLAY_COMPONENT_ENTITY_PROXY.h"

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( GAMEPLAY_COMPONENT_ENTITY_PROXY )

XS_END_INTERNAL_MEMORY_LAYOUT

GAMEPLAY_COMPONENT_ENTITY_PROXY::GAMEPLAY_COMPONENT_ENTITY_PROXY() :
    Entity( NULL ) {
        
}

GAMEPLAY_COMPONENT_ENTITY_PROXY::GAMEPLAY_COMPONENT_ENTITY_PROXY( GAMEPLAY_COMPONENT_ENTITY * entity ) :
    Entity( entity ) {
    
}
