//
//  GAMEPLAY_COMPONENT_MATERIAL.hpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 28/09/2020.
//  Copyright © 2020 Christophe Bernard. All rights reserved.
//

#ifndef GAMEPLAY_COMPONENT_MATERIAL_hpp
#define GAMEPLAY_COMPONENT_MATERIAL_hpp

#include "CORE_HELPERS_CLASS.h"
#include "CORE_HELPERS_FACTORY.h"
#include "GAMEPLAY_COMPONENT.h"
#include "GAMEPLAY_COMPONENT_TYPE.h"
#include "CORE_HELPERS_SCALAR.h"
#include "GRAPHIC_OBJECT.h"
#include "GRAPHIC_OBJECT_RESOURCE_LOADER.h"
#include "CORE_MATH_SHAPE.h"
#include "GAMEPLAY_COMPONENT_POSITION.h"
#include "RESOURCE_PROXY.h"
#include "GRAPHIC_MATERIAL.h"

class GAMEPLAY_COMPONENT_ENTITY;

XS_CLASS_BEGIN( GAMEPLAY_COMPONENT_RENDER_MATERIAL )

    GAMEPLAY_COMPONENT_RENDER_MATERIAL();
    ~GAMEPLAY_COMPONENT_RENDER_MATERIAL();

    XS_DEFINE_SERIALIZABLE

    //CORE_HELPERS_FACTORY_Element(GAMEPLAY_COMPONENT_RENDER, GAMEPLAY_COMPONENT, GAMEPLAY_COMPONENT_TYPE, GAMEPLAY_COMPONENT_TYPE_Render)

    static int
        ComponentType;

    GRAPHIC_MATERIAL_POCO
        Material;

XS_CLASS_END

#endif /* GAMEPLAY_COMPONENT_MATERIAL_hpp */
