//
//  GRAPHIC_SHADER_BIND.cpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 25/07/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#include "GRAPHIC_SHADER_BIND.h"
#include "CORE_HELPERS_CLASS.h"
#include "CORE_DATA_STREAM.h"

XS_CLASS_SERIALIZER_TemplateScalar( GRAPHIC_SHADER_BIND )

GRAPHIC_SHADER_BIND GRAPHIC_SHADER_BIND_PositionNormal = (GRAPHIC_SHADER_BIND)(GRAPHIC_SHADER_BIND_Position | GRAPHIC_SHADER_BIND_Normal);
GRAPHIC_SHADER_BIND GRAPHIC_SHADER_BIND_PositionNormalTexture = (GRAPHIC_SHADER_BIND)(GRAPHIC_SHADER_BIND_Position | GRAPHIC_SHADER_BIND_Normal | GRAPHIC_SHADER_BIND_Texcoord0 );
GRAPHIC_SHADER_BIND GRAPHIC_SHADER_BIND_PositionTexture = (GRAPHIC_SHADER_BIND)(GRAPHIC_SHADER_BIND_Position | GRAPHIC_SHADER_BIND_Texcoord0 );
GRAPHIC_SHADER_BIND GRAPHIC_SHADER_BIND_PositionNormalTextureTangentBitangent = (GRAPHIC_SHADER_BIND)(GRAPHIC_SHADER_BIND_Position | GRAPHIC_SHADER_BIND_Normal | GRAPHIC_SHADER_BIND_Texcoord0 | GRAPHIC_SHADER_BIND_Tangents | GRAPHIC_SHADER_BIND_Bitangents );