//
//  GRAPHIC_MESH_ANIMATION_MODE.h
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 26/01/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#ifndef __GAME_ENGINE_REBORN__GRAPHIC_MESH_ANIMATION_MODE__
#define __GAME_ENGINE_REBORN__GRAPHIC_MESH_ANIMATION_MODE__

enum GRAPHIC_MESH_ANIMATION_MODE {

    GRAPHIC_MESH_ANIMATION_MODE_Interpolation = 0,
    GRAPHIC_MESH_ANIMATION_MODE_Formula,
    GRAPHIC_MESH_ANIMATION_MODE_Count,
    GRAPHIC_MESH_ANIMATION_MODE_None
};

#endif /* defined(__GAME_ENGINE_REBORN__GRAPHIC_MESH_ANIMATION_MODE__) */
