//
//  GRAPHIC_MESH_ANIMATION_COLLECTION.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 14/08/2020.
//  Copyright © 2020 Christophe Bernard. All rights reserved.
//

#include "GRAPHIC_MESH_ANIMATION_COLLECTION.h"
#include "GRAPHIC_MESH_ANIMATION_COLLECTION_RESOURCE_LOADER.h"
#include "CORE_DATA_STREAM.h"
#include "CORE_DATA_LOADER.h"
#include "CORE_DATA_JSON.h"

XS_IMPLEMENT_INTERNAL_MEMORY_LAYOUT( GRAPHIC_MESH_ANIMATION_COLLECTION )
    XS_DEFINE_ClassMember( "AnimationTable", std::vector< GRAPHIC_MESH_ANIMATION::PTR >, AnimationTable )
XS_END_INTERNAL_MEMORY_LAYOUT

GRAPHIC_MESH_ANIMATION_COLLECTION::GRAPHIC_MESH_ANIMATION_COLLECTION() :
    GR_A_GRAPHIC_MESH_ANIMATION_COLLECTION_ANCESTOR_TYPE(),
    AnimationTable() {
    
}

GRAPHIC_MESH_ANIMATION_COLLECTION::~GRAPHIC_MESH_ANIMATION_COLLECTION() {
    
}

GRAPHIC_MESH_ANIMATION_COLLECTION::GRAPHIC_MESH_ANIMATION_COLLECTION( const GRAPHIC_MESH_ANIMATION_COLLECTION & other ) : AnimationTable( other.AnimationTable ){
    
}


void GRAPHIC_MESH_ANIMATION_COLLECTION::operator= ( const GRAPHIC_MESH_ANIMATION_COLLECTION & other ) {
    abort();
}
