//
//  PERIPHERIC_INTERACTION_TOUCH.cpp
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 16/04/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#include "PERIPHERIC_INTERACTION_TOUCH.h"

CORE_ABSTRACT_PROGRAM_BINDER_DECLARE_CLASS( PERIPHERIC_INTERACTION_TOUCH )
    CORE_ABSTRACT_PROGRAM_BINDER_DEFINE_YIELD_METHOD( float, PERIPHERIC_INTERACTION_TOUCH, GetX )
    CORE_ABSTRACT_PROGRAM_BINDER_DEFINE_YIELD_METHOD( float, PERIPHERIC_INTERACTION_TOUCH, GetY )
    CORE_ABSTRACT_PROGRAM_BINDER_DEFINE_YIELD_METHOD( float, PERIPHERIC_INTERACTION_TOUCH, GetZ )
CORE_ABSTRACT_PROGRAM_BINDER_END_CLASS( PERIPHERIC_INTERACTION_TOUCH )

PERIPHERIC_INTERACTION_TOUCH::PERIPHERIC_INTERACTION_TOUCH() :
    X( 0.0f ),
    Y( 0.0f ),
    Z( 0.0f ) {
    
}

PERIPHERIC_INTERACTION_TOUCH::~PERIPHERIC_INTERACTION_TOUCH() {

}

void PERIPHERIC_INTERACTION_TOUCH::Update( float time_step, float accel_x, float accel_y, float accel_z ) {
    X = accel_x;
    Y = accel_y;
    Z = accel_z;
}
