//
//  PERIPHERIC_INTERACTION_SYSTEM.cpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 29/03/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#include "PERIPHERIC_INTERACTION_SYSTEM.h"

CORE_ABSTRACT_PROGRAM_BINDER_DECLARE_CLASS( PERIPHERIC_INTERACTION_SYSTEM )
    CORE_ABSTRACT_PROGRAM_BINDER_DEFINE_STATIC_YIELD_METHOD( PERIPHERIC_INTERACTION_SYSTEM &, PERIPHERIC_INTERACTION_SYSTEM, GetInstance )
    CORE_ABSTRACT_PROGRAM_BINDER_DEFINE_YIELD_METHOD( PERIPHERIC_INTERACTION_KEYBOARD &, PERIPHERIC_INTERACTION_SYSTEM, GetKeyboard )
    CORE_ABSTRACT_PROGRAM_BINDER_DEFINE_YIELD_METHOD( PERIPHERIC_INTERACTION_MOUSE &, PERIPHERIC_INTERACTION_SYSTEM, GetMouse )
    CORE_ABSTRACT_PROGRAM_BINDER_DEFINE_YIELD_METHOD( PERIPHERIC_INTERRACTION_VIBRATOR &, PERIPHERIC_INTERACTION_SYSTEM, GetVibrator )
CORE_ABSTRACT_PROGRAM_BINDER_END_CLASS( PERIPHERIC_INTERACTION_SYSTEM )

PERIPHERIC_INTERACTION_SYSTEM::PERIPHERIC_INTERACTION_SYSTEM() :
    Keyboard(),
    Mouse(),
    Vibrator() {
    
    Keyboard.Initialize();
    Mouse.Initialize();
}

PERIPHERIC_INTERACTION_SYSTEM::~PERIPHERIC_INTERACTION_SYSTEM() {

}

void PERIPHERIC_INTERACTION_SYSTEM::Update() {
    
    Keyboard.Update();
    Mouse.Update();
}
