//
//  APPLICATION_MULTIPLAYER_HUD_PRESENTER.cpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 23/01/17.
//  Copyright © 2017 Christophe Bernard. All rights reserved.
//

#include "APPLICATION_MULTIPLAYER_HUD_PRESENTER.h"

APPLICATION_MULTIPLAYER_HUD_PRESENTER::APPLICATION_MULTIPLAYER_HUD_PRESENTER() :
    APPLICATION_HUD_PRESENTER() {
    
}

APPLICATION_MULTIPLAYER_HUD_PRESENTER::~APPLICATION_MULTIPLAYER_HUD_PRESENTER() {
    
}

void APPLICATION_MULTIPLAYER_HUD_PRESENTER::Update( const float time_step ) {
    
}

void APPLICATION_MULTIPLAYER_HUD_PRESENTER::Configure() {
    
}
