//
//  SERVICE_NETWORK_CONNECTION_TYPE.h
//  GAME-ENGINE
//
//  Created by Christophe Bernard on 8/09/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#ifndef GAME_ENGINE_REBORN_SERVICE_NETWORK_CONNECTION_TYPE_h
#define GAME_ENGINE_REBORN_SERVICE_NETWORK_CONNECTION_TYPE_h

enum SERVICE_NETWORK_CONNECTION_TYPE {
    SERVICE_NETWORK_CONNECTION_TYPE_Udp = 0,
    SERVICE_NETWORK_CONNECTION_TYPE_Tcp,
    SERVICE_NETWORK_CONNECTION_TYPE_TcpAccept,
    SERVICE_NETWORK_CONNECTION_TYPE_Count,
    SERVICE_NETWORK_CONNECTION_TYPE_None
};

#endif
