//
//  GAMEPLAY_COMPONENT_SYSTEM_ANIMATION_BLENDING.cpp
//  GAME-ENGINE-REBORN
//
//  Created by Christophe Bernard on 31/03/15.
//  Copyright (c) 2015 Christophe Bernard. All rights reserved.
//

#include "GAMEPLAY_COMPONENT_SYSTEM_ANIMATION_BLENDING.h"

GAMEPLAY_COMPONENT_SYSTEM_ANIMATION_BLENDING::GAMEPLAY_COMPONENT_SYSTEM_ANIMATION_BLENDING() {

}

GAMEPLAY_COMPONENT_SYSTEM_ANIMATION_BLENDING::~GAMEPLAY_COMPONENT_SYSTEM_ANIMATION_BLENDING() {

}

void GAMEPLAY_COMPONENT_SYSTEM_ANIMATION_BLENDING::Initialize() {

}

void GAMEPLAY_COMPONENT_SYSTEM_ANIMATION_BLENDING::Update( float time_step ) {

}

void GAMEPLAY_COMPONENT_SYSTEM_ANIMATION_BLENDING::Render() {

}

void GAMEPLAY_COMPONENT_SYSTEM_ANIMATION_BLENDING::Finalize() {

}